### ISSUE TITLE
Document configuration & initialization

### ISSUE THREAD

**Issue by jorygeerts** [cmpayments/payments-sdk-net#21]
Please add documentation describing how to initialize and configure the `PaymentClient` class to the readme.

This information is currently documented at https://docs.cmtelecom.com/payments/v0.3, but it does not belong there.

**Comment by mvesign** [comment]
Added examples on how to initialize the PaymentClient model, to the README. Re-used parts of the information, displayed on the documentation page, for this. Close issue.
