### ISSUE TITLE
Failed to build on case-sensitive environment: Linux/Mac OS and Docker container with Unix base

### ISSUE THREAD

**Issue by lunmatu101** [cmpayments/payments-sdk-net#33]
## Expected Behavior
The .NET Core was popular and we can build and run it on Linux/MAC OS and Docker container as well.

## Current Behavior
But this SDK was failed when building on the case-sensitive environment.

## Possible Solution
Be careful when naming uppercase file/directory

## Steps to Reproduce
1. Just cloned source code and build on Linux/MAC OS or add it to Dockerfile as a project reference 
2. Run dotnet build or docker build and see the errors afterward

`Build FAILED.
CSC : error CS2001: Source file '/src/Source/CM.Payments.Client.Shared/Model/Qr/QrRequest.cs' could not be found. [/src/Source/CM.Payments.Client.Core/CM.Payments.Client.Core.csproj]
CSC : error CS2001: Source file '/src/Source/CM.Payments.Client.Shared/Model/Qr/QrResponse.cs' could not be found. [/src/Source/CM.Payments.Client.Core/CM.Payments.Client.Core.csproj]`
## Context (Environment)
- Linux/MAC OS
- Docker container with Unix base

## Possible Implementation
- Change `<Compile Include="$(MSBuildThisFileDirectory)Model\Qr\QrRequest.cs" />` to `<Compile Include="$(MSBuildThisFileDirectory)Model\QR\QrRequest.cs" />`
- Change `<Compile Include="$(MSBuildThisFileDirectory)Model\Qr\QrResponse.cs" />` to `<Compile Include="$(MSBuildThisFileDirectory)Model\QR\QrResponse.cs" />`

**Comment by baspeters** [comment]
Thanks for your contribution. This fix is now available on NuGET:
https://www.nuget.org/packages/CM.Payments.SDK/1.2.5.83
