### ISSUE TITLE
Can not install SDK on .NET Core application

### ISSUE THREAD

**Issue by lunmatu101** [cmpayments/payments-sdk-net#34]
## Expected Behavior
Possible to install SDK on .NET core 1.x 2.x and 3.x or varying .NET standard versions

## Current Behavior
But when trying to install SDK to .NET core it always installs SDK with .NET framework version. That caused many errors with dependencies

## Possible Solution
Update the Nuget spec to match with correct target framework version

## Steps to Reproduce
1. Create new .NET core project
2. Installl SDK to project
3. Warning from IDE
`Warning	NU1701	Package 'CM.Payments.SDK 1.2.4.76' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project`
4. Run project and it will throw many errors about dependecies
`System.IO.FileNotFoundException: 'Could not load file or assembly 'FluentValidation, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7de548da2fbae0f0'. The system cannot find the file specified.'`
5. It even caused error on BaseValidator that check with NETSTANDARD1_6 condition
` Unhandled exception. System.Globalization.CultureNotFoundException: Culture is not supported. (Parameter 'culture')
   4096 (0x1000) is an invalid culture identifier.
   at System.Globalization.CultureData.GetCultureData(Int32 culture, Boolean bUseUserOverride)
   at System.Globalization.RegionInfo..ctor(Int32 culture)`

## Context (Environment)
- .NET core
- ASP.NET core

## Possible Implementation
- Change `<group targetFramework="netcore">` to `<group targetFramework="netstandard1.6">`
- If we really want to validate Currency on other .NET standard versions base on system localization . We can update by below:
`private static readonly IEnumerable<string> CurrencySymbols = CultureInfo.GetCultures(CultureTypes.SpecificCultures)
            .Select(x => new RegionInfo(x.LCID).ISOCurrencySymbol)
            .Distinct()
            .OrderBy(x => x);`
TO
`private static readonly IEnumerable<string> CurrencySymbols = CultureInfo.GetCultures(CultureTypes.SpecificCultures)
            .Select(x => new RegionInfo(x.Name).ISOCurrencySymbol)
            .Distinct()
            .OrderBy(x => x);`
But if not, with .NET core app it always return true.

**Comment by baspeters** [comment]
Thanks for your contribution. This fix is now available on NuGET:
https://www.nuget.org/packages/CM.Payments.SDK/1.2.5.83
